baseURL = "https://www.bergerdental.com"
title = "Berger Dental"
theme = "universal"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableRobotsTXT = true
canonifyURLs = true

# Define the number of posts per page
paginate = 2

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "patients"
    name = "New Patients"
    url  = "/patients/"
    weight = 2

[[menu.main]]
    identifier = "insurance"
    name = "Insurance"
    url  = "/insurance/"
    weight = 3

[[menu.main]]
    identifier = "procedures"
    name = "Procedures"
    url  = "/procedures/"
    weight = 4

[[menu.main]]
    identifier = "financing"
    name = "Financing"
    url  = "/financing/"
    weight = 5

[[menu.main]]
    identifier = "staff"
    name = "Staff"
    url  = "/staff/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "phone"
    url = "tel:940-566-1828"
    pre = "<i class='fas fa-2x fa-mobile-alt'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/Berger-Dental-119075571458053/"
    pre = "<i class='fab fa-2x fa-facebook'></i>" 

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:bergerdental@bergerdental.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"



# Top par contact us
[params.topbar]
    enable = true
    text = "Call or Text us --------->"

[params.features]
    enable = true

[params.carousel]
    enable = true	
	
[params]

	author = "BergerDental"
	facebook = "https://www.facebook.com/groups/230607091341050"
	sitename = "Berger Dental - Denton, Texas 76201"
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"
	
	logo = "img/logo.png"
	logo_small = "img/logo.png"
	
    about_us = "<p>Berger Dental is a general dentistry office located in Denton, TX. Serving Denton County and the greater Dallas-Fort Worth metroplex since 2002.</p>"
    copyright = "Copyright (c) 2014 - 2024, BergerDental; all rights reserved."
    # Format dates with Go's time formatting
    date_format = "January 13, 2021"
    
	address = """<p class="text-uppercase"><strong>Berger Dental</strong>
        <br>1010 N Elm
        <br>Denton, TX
        <br>76201</p>"""
		
[languages]	
	[languages.en]
		languageName = "English"
		languageCode = "en-us"
		weight = "1"
